compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1"
          - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
          - "@uniswap/v3-periphery=Uniswap/v3-periphery@1.3.0"
